#!/bin/bash
echo "Cleaning up & setting .version"
make clean
echo "1" > .version
echo "Loading Racer gen2 defconfig..."
make cyanogen_mooncake_defconfig
echo "Compiling kernel..."
make -j4
cd ~/android/nightlies/cm7/racer
echo "Copying zImage..."
cp ~/android/cm7/kernel/zte/msm7x27/arch/arm/boot/zImage zImage
echo "Creating gen2_boot.img..."
mkbootimg --base 0x02600000 --kernel zImage --ramdisk ../ramdisk.gz -o gen2_boot.img
echo "Done! gen2_boot.img is ready"
