#!/bin/bash
echo "Cleaning up & setting .version"
make clean
echo "1" > .version
echo "Loading recovery gen2 defconfig..."
make cyanogen_mooncake_recovery_defconfig
echo "Compiling kernel..."
make -j4
cd ~/android/nightlies/cm7/recovery
echo "Copying zImage..."
cp ~/android/cm7/kernel/zte/msm7x27/arch/arm/boot/zImage zImage
echo "Creating gen2_recovery.img..."
mkbootimg --base 0x02600000 --cmdline 'androidboot.hardware=mooncake console=null' --kernel zImage --ramdisk ramdisk.gz -o recovery/gen2_recovery.img
echo "Done! gen2_recovery.img is ready"
