#!/bin/bash
echo "Cleaning up & setting .version"
make clean
echo "1" > .version
echo "Loading recovery gen1 defconfig..."
make cyanogen_mooncake_recovery_gen1_defconfig
echo "Compiling kernel..."
make -j4
cd ~/android/nightlies/cm7/recovery
echo "Copying zImage..."
cp ~/android/cm7/kernel/zte/msm7x27/arch/arm/boot/zImage zImage
echo "Creating gen1_recovery.img..."
mkbootimg --base 0x02A00000 --kernel zImage --ramdisk ../ramdisk.gz -o gen1_recovery.img
echo "Done! gen1_recovery.img is ready"
